apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ../../crds/juggernaut.io_servertypes.yaml
  - ../../crds/juggernaut.io_sessions.yaml
  - rbac.yaml
  - redis.yaml
  - gateway.yaml
  - controller.yaml
configMapGenerator:
  - name: juggernaut-config
    namespace: juggernaut-system
    files:
      - juggernaut.yaml
    options:
      disableNameSuffixHash: true   # the binaries hot-reload the mounted file
