{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "juggernaut.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "juggernaut.labels" . | nindent 4 }}
type: Opaque
data:
  broker-client-secret: {{ .Values.secrets.brokerClientSecret | b64enc | quote }}
  introspection-client-secret: {{ .Values.secrets.introspectionClientSecret | b64enc | quote }}
  keycloak-admin-secret: {{ .Values.secrets.keycloakAdminSecret | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  kek: {{ .Values.secrets.kek | default (randBytes 32) | quote }}
{{- end }}
